# Generated by Django 5.2.3 on 2025-07-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('coach_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('founded_year', models.IntegerField()),
            ],
            options={
                'db_table': 'franchise',
            },
        ),
    ]
