# Generated by Django 5.2.3 on 2025-07-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IplApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='franchises_logos'),
        ),
    ]
