# Generated by Django 5.2.3 on 2025-07-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IplApp', '0002_franchise_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveBigIntegerField()),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('Wicket-Keeper', 'Wicket-Keeper')], max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IplApp.franchise')),
            ],
        ),
    ]
