# Generated by Django 5.2.3 on 2025-07-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IplApp', '0004_alter_player_photo_stadium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadium',
            old_name='estblished_year',
            new_name='established_year',
        ),
    ]
